####### Release-2.0.0

__yarn_host__: "{{ groups['yarn-master'][0] }}"
zookeepers: "{{groups['zookeeper']|join(':2181,')}}:2181"
kafka_brokers: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
